// <auto-generated />
using System;
using Appva_test.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Appva_test.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20190224165559_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Appva_test.Models.DateItem", b =>
                {
                    b.Property<int>("DateItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DueDate");

                    b.HasKey("DateItemId");

                    b.ToTable("DateItems");
                });

            modelBuilder.Entity("Appva_test.Models.TodoItem", b =>
                {
                    b.Property<int>("TodoItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DateItemId");

                    b.Property<string>("Desc");

                    b.Property<bool>("IsDone");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("TodoItemId");

                    b.HasIndex("DateItemId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Appva_test.Models.TodoItem", b =>
                {
                    b.HasOne("Appva_test.Models.DateItem")
                        .WithMany("TodoItems")
                        .HasForeignKey("DateItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
